-- MySQL Script generated by MySQL Workbench
-- 11/22/16 13:19:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` DEFAULT CHARACTER SET utf8 ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`university` (
  `university_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`university_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `university_id` INT NOT NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `university_university_id_idx` (`university_id` ASC),
  CONSTRAINT `university_university_id`
    FOREIGN KEY (`university_id`)
    REFERENCES `University`.`university` (`university_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_number` INT NOT NULL,
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`group_id`),
  INDEX `faculty_faculty_id_idx` (`faculty_id` ASC),
  UNIQUE INDEX `group_number_UNIQUE` (`group_number` ASC),
  CONSTRAINT `faculty_faculty_id`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `University`.`faculty` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `e_mail` VARCHAR(60) NOT NULL,
  `study_year` ENUM('FIRST', 'SECOND', 'THIRD', 'FOURTH') NOT NULL,
  `study_semester` ENUM('FIRST', 'SECOND') NOT NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC),
  INDEX `group_groupid_idx` (`group_id` ASC),
  CONSTRAINT `group_groupid`
    FOREIGN KEY (`group_id`)
    REFERENCES `University`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `e_mail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `week_day` ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY') NOT NULL,
  `course_time` ENUM('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'SEVENTH') NOT NULL,
  `professor_id` INT NULL,
  `auditorium_num` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `professor_professor_id_idx` (`professor_id` ASC),
  UNIQUE INDEX `subject_UNIQUE` (`subject` ASC),
  CONSTRAINT `professor_professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `University`.`professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`group_course_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`group_course_map` (
  `group_course_map_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`group_course_map_id`),
  INDEX `group_group_id_idx` (`group_id` ASC),
  INDEX `couse_course_id_idx` (`course_id` ASC),
  CONSTRAINT `group_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `University`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `couse_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `University`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
